# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'
  folderName: 'back-end/CRUD'
  projectName: 'CRUD'

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'pack'
    arguments: --output $(build.artifactstagingdirectory) --configuration $(buildConfiguration)
    packagesToPack: '$(folderName)/$(projectName).csproj'
    versioningScheme: byPrereleaseNumber
    versionEnvVar: byPrereleaseNumber
    majorVersion: 0
    minorVersion: 1
    patchVersion: 0

- task: DotNetCoreCLI@2
  inputs:
    command: 'push'
    nuGetFeedType: 'internal'
    packagesToPush: '$(build.artifactStagingDirectory)/*.nupkg'
    publishVstsFeed: "TeamFeed"

- task: PublishBuildArtifacts@1